name: Build and Push to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::223767250051:role/orderflow-github-actions-role
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        working-directory: ./app
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/orderflow-api:${{ github.sha }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/orderflow-api:${{ github.sha }}
          docker tag ${{ steps.login-ecr.outputs.registry }}/orderflow-api:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/orderflow-api:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/orderflow-api:latest
